-- MySQL Script generated by MySQL Workbench
-- 04/30/17 22:39:33
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema evaluacion
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema evaluacion
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `evaluacion` DEFAULT CHARACTER SET utf8 ;
USE `evaluacion` ;

-- -----------------------------------------------------
-- Table `evaluacion`.` usuarios`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `evaluacion`.` usuarios` (
  `id_persona` INT(11) NOT NULL COMMENT '',
  `nom_usuario` VARCHAR(45) NOT NULL COMMENT '',
  `clave` VARCHAR(100) NOT NULL COMMENT '',
  `id_estatus` VARCHAR(10) NULL DEFAULT NULL COMMENT '',
  `creado_por` INT(11) NULL DEFAULT NULL COMMENT '',
  `fec_creado` DATETIME NULL DEFAULT NULL COMMENT '',
  `actualizado_por` INT(11) NULL DEFAULT NULL COMMENT '',
  `fec_actualizado` DATETIME NULL DEFAULT NULL COMMENT '',
  PRIMARY KEY (`id_persona`)  COMMENT '',
  INDEX `id_persona_idx` (`id_persona` ASC)  COMMENT '')
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `evaluacion`.`estatus`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `evaluacion`.`estatus` (
  `id_estatus` INT(11) NOT NULL AUTO_INCREMENT COMMENT '',
  `nom_estatus` VARCHAR(45) NULL DEFAULT NULL COMMENT '',
  `creado_por` INT(11) NULL DEFAULT NULL COMMENT '',
  `fec_creado` DATETIME NULL DEFAULT NULL COMMENT '',
  `actualizado_por` INT(11) NULL DEFAULT NULL COMMENT '',
  `fec_actualizado` DATETIME NULL DEFAULT NULL COMMENT '',
  PRIMARY KEY (`id_estatus`)  COMMENT '')
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `evaluacion`.`ubicaciones`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `evaluacion`.`ubicaciones` (
  `id_ubicacion` INT(11) NOT NULL AUTO_INCREMENT COMMENT '',
  `nom_ubicacion` VARCHAR(100) NOT NULL COMMENT '',
  `id_personas` INT(11) NULL DEFAULT NULL COMMENT '',
  `creado_por` INT(11) NULL DEFAULT NULL COMMENT '',
  `fec_creado` DATETIME NULL DEFAULT NULL COMMENT '',
  `actualizado_por` INT(11) NULL DEFAULT NULL COMMENT '',
  `fec_actualizado` DATETIME NULL DEFAULT NULL COMMENT '',
  PRIMARY KEY (`id_ubicacion`)  COMMENT '',
  INDEX `id_personas` (`id_personas` ASC)  COMMENT '',
  CONSTRAINT `id_personas`
    FOREIGN KEY (`id_personas`)
    REFERENCES `evaluacion`.`personas` (`id_persona`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `evaluacion`.`personas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `evaluacion`.`personas` (
  `id_persona` INT(11) NOT NULL AUTO_INCREMENT COMMENT '',
  `pri_nom` VARCHAR(45) NOT NULL COMMENT '',
  `seg_nom` VARCHAR(45) NULL DEFAULT NULL COMMENT '',
  `pri_ape` VARCHAR(45) NOT NULL COMMENT '',
  `seg_ape` VARCHAR(45) NULL DEFAULT NULL COMMENT '',
  `tip_documento` VARCHAR(45) NOT NULL COMMENT '',
  `num_documento` VARCHAR(45) NOT NULL COMMENT '',
  `sexo` VARCHAR(45) NULL DEFAULT NULL COMMENT '',
  `edo_civil` VARCHAR(45) NULL DEFAULT NULL COMMENT '',
  `fec_nacimiento` DATE NULL DEFAULT NULL COMMENT '',
  `id_estatus` INT(11) NULL DEFAULT NULL COMMENT '',
  `cargo` VARCHAR(45) NOT NULL COMMENT '',
  `creado_por` INT(11) NULL DEFAULT NULL COMMENT '',
  `fec_creado` DATETIME NULL DEFAULT NULL COMMENT '',
  `actualizado_por` INT(11) NULL DEFAULT NULL COMMENT '',
  `fec_actualizado` DATETIME NULL DEFAULT NULL COMMENT '',
  `id_ubicacion` INT(11) NULL DEFAULT NULL COMMENT '',
  `fec_ingreso` DATETIME NULL DEFAULT NULL COMMENT '',
  PRIMARY KEY (`id_persona`)  COMMENT '',
  INDEX `fk_id_estatu` (`id_estatus` ASC)  COMMENT '',
  INDEX `id_ubicacion` (`id_ubicacion` ASC)  COMMENT '',
  CONSTRAINT `fk_id_estatu`
    FOREIGN KEY (`id_estatus`)
    REFERENCES `evaluacion`.`estatus` (`id_estatus`),
  CONSTRAINT `id_ubicacion`
    FOREIGN KEY (`id_ubicacion`)
    REFERENCES `evaluacion`.`ubicaciones` (`id_ubicacion`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `evaluacion`.`competencias`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `evaluacion`.`competencias` (
  `id_competencia` INT(11) NOT NULL AUTO_INCREMENT COMMENT '',
  `id_persona` INT(11) NULL DEFAULT NULL COMMENT '',
  `fec_aplicacion` DATETIME NULL DEFAULT NULL COMMENT '',
  `calificacion` DECIMAL(10,0) NULL DEFAULT NULL COMMENT '',
  `competencias` VARCHAR(1000) NULL DEFAULT NULL COMMENT '',
  `creado_por` INT(11) NULL DEFAULT NULL COMMENT '',
  `fec_creado` DATETIME NULL DEFAULT NULL COMMENT '',
  `actualizado_por` INT(11) NULL DEFAULT NULL COMMENT '',
  `fec_actualizado` DATETIME NULL DEFAULT NULL COMMENT '',
  `revisado_por` INT(11) NULL DEFAULT NULL COMMENT '',
  `val_peso` DECIMAL(10,0) NULL DEFAULT NULL COMMENT '',
  PRIMARY KEY (`id_competencia`)  COMMENT '',
  INDEX `id_person` (`id_persona` ASC)  COMMENT '',
  CONSTRAINT `id_person`
    FOREIGN KEY (`id_persona`)
    REFERENCES `evaluacion`.`personas` (`id_persona`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `evaluacion`.`evaluacion_resultado`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `evaluacion`.`evaluacion_resultado` (
  `id_evaluacion` INT(11) NULL DEFAULT NULL COMMENT '',
  `id_proc` INT(11) NULL DEFAULT NULL COMMENT '')
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `evaluacion`.`procesos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `evaluacion`.`procesos` (
  `id_proc` INT(20) NOT NULL AUTO_INCREMENT COMMENT '',
  `descripcion` VARCHAR(500) NULL DEFAULT NULL COMMENT '',
  `fec_desde` DATE NULL DEFAULT NULL COMMENT '',
  `fec_hasta` DATE NULL DEFAULT NULL COMMENT '',
  `fec_apertura_competencias` DATE NULL COMMENT '',
  `fec_cierre_competencias` DATE NULL COMMENT '',
  PRIMARY KEY (`id_proc`)  COMMENT '')
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `evaluacion`.`evaluaciones`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `evaluacion`.`evaluaciones` (
  `id_evaluaciones` INT(11) NOT NULL AUTO_INCREMENT COMMENT '',
  `id_persona` INT(11) NOT NULL COMMENT '',
  `id_cargo` INT(11) NOT NULL COMMENT '',
  `id_ubicacion` INT(11) NOT NULL COMMENT '',
  `id_proc` INT(11) NULL DEFAULT NULL COMMENT '',
  `objetivos` VARCHAR(2000) NOT NULL COMMENT '',
  `creado_por` INT(11) NULL DEFAULT NULL COMMENT '',
  `fec_creado` DATETIME NULL DEFAULT NULL COMMENT '',
  `actualizado_por` INT(11) NULL DEFAULT NULL COMMENT '',
  `fec_actualizado` DATETIME NULL DEFAULT NULL COMMENT '',
  `revisado_por` INT(11) NULL DEFAULT NULL COMMENT '',
  PRIMARY KEY (`id_evaluaciones`, `id_persona`, `id_cargo`, `id_ubicacion`)  COMMENT '',
  INDEX `fk_id_personas` (`id_persona` ASC)  COMMENT '',
  INDEX `fk_id_cargos` (`id_cargo` ASC)  COMMENT '',
  INDEX `id_proceso` (`id_proc` ASC)  COMMENT '',
  CONSTRAINT `id_proceso`
    FOREIGN KEY (`id_proc`)
    REFERENCES `evaluacion`.`procesos` (`id_proc`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `evaluacion`.`evaluadores`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `evaluacion`.`evaluadores` (
  `id_evaluador` INT(11) NOT NULL COMMENT '',
  `id_cargo` INT(11) NULL DEFAULT NULL COMMENT '',
  `id_persona` INT(11) NULL DEFAULT NULL COMMENT '',
  `id_ubicacion` INT(11) NULL DEFAULT NULL COMMENT '',
  `fec_asignacion` DATETIME NULL DEFAULT NULL COMMENT '',
  `id_proc` INT(11) NULL DEFAULT NULL COMMENT '',
  PRIMARY KEY (`id_evaluador`)  COMMENT '',
  INDEX `id_per` (`id_persona` ASC)  COMMENT '',
  INDEX `fk_id_ubicacion` (`id_ubicacion` ASC)  COMMENT '',
  CONSTRAINT `fk_id_ubicacion`
    FOREIGN KEY (`id_ubicacion`)
    REFERENCES `evaluacion`.`ubicaciones` (`id_ubicacion`),
  CONSTRAINT `id_per`
    FOREIGN KEY (`id_persona`)
    REFERENCES `evaluacion`.`personas` (`id_persona`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `evaluacion`.`menu`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `evaluacion`.`menu` (
  `id menu` INT(11) NOT NULL COMMENT '',
  `id_menu_padre` INT(11) NOT NULL COMMENT '',
  `nom_menu` VARCHAR(45) NOT NULL COMMENT '',
  `orden` INT(11) NULL DEFAULT NULL COMMENT '',
  `url` VARCHAR(45) NULL DEFAULT NULL COMMENT '',
  `id_estatus` INT(11) NULL DEFAULT NULL COMMENT '',
  `creado_por` INT(11) NULL DEFAULT NULL COMMENT '',
  `fec_creado` DATETIME NULL DEFAULT NULL COMMENT '',
  `actualizado_por` INT(11) NULL DEFAULT NULL COMMENT '',
  `fec_actualizado` DATETIME NULL DEFAULT NULL COMMENT '',
  PRIMARY KEY (`id menu`)  COMMENT '',
  INDEX `fk_id_menu_padre` (`id_menu_padre` ASC)  COMMENT '',
  INDEX `fk_if_estatus` (`id_estatus` ASC)  COMMENT '',
  CONSTRAINT `fk_id_menu_padre`
    FOREIGN KEY (`id_menu_padre`)
    REFERENCES `evaluacion`.`menu` (`id menu`),
  CONSTRAINT `fk_if_estatus`
    FOREIGN KEY (`id_estatus`)
    REFERENCES `evaluacion`.`estatus` (`id_estatus`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `evaluacion`.`roles`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `evaluacion`.`roles` (
  `id_rol` INT(11) NOT NULL AUTO_INCREMENT COMMENT '',
  `nom_rol` VARCHAR(45) NOT NULL COMMENT '',
  `id_estatus` INT(11) NULL DEFAULT NULL COMMENT '',
  `creado_por` INT(11) NULL DEFAULT NULL COMMENT '',
  `fec_creado` DATETIME NULL DEFAULT NULL COMMENT '',
  `actualizado_por` INT(11) NULL DEFAULT NULL COMMENT '',
  `fec_actualizado` DATETIME NULL DEFAULT NULL COMMENT '',
  PRIMARY KEY (`id_rol`)  COMMENT '')
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `evaluacion`.`menu_rol`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `evaluacion`.`menu_rol` (
  `id_menu` INT(11) NOT NULL COMMENT '',
  `id_rol` INT(11) NOT NULL COMMENT '',
  `id_estatus` INT(11) NULL DEFAULT NULL COMMENT '',
  `creado_por` INT(11) NULL DEFAULT NULL COMMENT '',
  `fec_creado` DATETIME NULL DEFAULT NULL COMMENT '',
  `actualizado_por` INT(11) NULL DEFAULT NULL COMMENT '',
  `fec_actualizado` DATETIME NULL DEFAULT NULL COMMENT '',
  PRIMARY KEY (`id_menu`)  COMMENT '',
  INDEX `id_rol_idx` (`id_rol` ASC)  COMMENT '',
  INDEX `id_estatus_idx` (`id_estatus` ASC)  COMMENT '',
  CONSTRAINT `id_estatus`
    FOREIGN KEY (`id_estatus`)
    REFERENCES `evaluacion`.`estatus` (`id_estatus`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `id_menu`
    FOREIGN KEY (`id_menu`)
    REFERENCES `evaluacion`.`menu` (`id menu`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `id_rol`
    FOREIGN KEY (`id_rol`)
    REFERENCES `evaluacion`.`roles` (`id_rol`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `evaluacion`.`odis`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `evaluacion`.`odis` (
  `id_odi` INT(11) NOT NULL AUTO_INCREMENT COMMENT '',
  `descripcion` INT(11) NOT NULL COMMENT '',
  `orden` INT(3) NULL DEFAULT NULL COMMENT '',
  `val_peso` DECIMAL(3,0) NULL DEFAULT NULL COMMENT '',
  PRIMARY KEY (`id_odi`)  COMMENT '')
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `evaluacion`.`usuarios_roles`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `evaluacion`.`usuarios_roles` (
  `id_persona` INT(11) NOT NULL AUTO_INCREMENT COMMENT '',
  `id_rol` INT(11) NOT NULL COMMENT '',
  `creado_por` INT(11) NULL DEFAULT NULL COMMENT '',
  `fec_creado` DATETIME NULL DEFAULT NULL COMMENT '',
  `actualizado_por` INT(11) NULL DEFAULT NULL COMMENT '',
  `fec_actualizado` DATETIME NULL DEFAULT NULL COMMENT '',
  `id_estatus` INT(11) NOT NULL COMMENT '',
  PRIMARY KEY (`id_persona`, `id_rol`)  COMMENT '',
  INDEX `id_rol_idx` (`id_rol` ASC)  COMMENT '',
  INDEX `fk_estatus` (`id_estatus` ASC)  COMMENT '',
  CONSTRAINT `fk_estatus`
    FOREIGN KEY (`id_estatus`)
    REFERENCES `evaluacion`.`estatus` (`id_estatus`),
  CONSTRAINT `fk_persona`
    FOREIGN KEY (`id_persona`)
    REFERENCES `evaluacion`.`personas` (`id_persona`),
  CONSTRAINT `fk_roles`
    FOREIGN KEY (`id_rol`)
    REFERENCES `evaluacion`.`roles` (`id_rol`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
